-- FAQ FK 제약조건 추가

-- FAQ_BOARD - ADMIN 연결
ALTER TABLE FAQ_BOARD
ADD FOREIGN KEY(ADMIN_NO)
REFERENCES ADMIN(ADMIN_NO);

-- FAQ_BOARD - FAQ_CATEGORY 연결
ALTER TABLE FAQ_BOARD
ADD FOREIGN KEY(FAQ_CATEGORY_NO)
REFERENCES FAQ_CATEGORY(FAQ_CATEGORY_NO);

--------------------------------------------------------------------------------

-- 리뷰게시판 FK 제약조건 추가

-- REVIEW - MEMBER 연결
ALTER TABLE REVIEW
ADD FOREIGN KEY(MEMBER_NO)
REFERENCES MEMBER(MEMBER_NO);

-- REVIEW - PRODUCT 연결
ALTER TABLE REVIEW
ADD FOREIGN KEY(P_CD)
REFERENCES PRODUCT(P_CD);

-- REVIEW - PRODUCT_ORDER 연결
ALTER TABLE REVIEW
ADD FOREIGN KEY(P_ORDER_CD)
REFERENCES PRODUCT_ORDER(P_ORDER_CD);

-- REVIEW - SUBS_ORDER 연결
ALTER TABLE REVIEW
ADD FOREIGN KEY(S_ORDER_CD)
REFERENCES SUBS_ORDER(S_ORDER_CD);


-- 리뷰 이미지 FK 추가
-- REVIEW_IMG - REVIEW 연결
ALTER TABLE REVIEW_IMG
ADD FOREIGN KEY(REVIEW_NO)
REFERENCES REVIEW(REVIEW_NO);

--------------------------------------------------------------------------------

-- 개별 상품 주문 FK 추가

-- PRODUCT_ORDER - MEMBER 연결
ALTER TABLE PRODUCT_ORDER
ADD FOREIGN KEY(MEMBER_NO)
REFERENCES MEMBER(MEMBER_NO);

-- PRODUCT_ORDER - PRODUCT_DELIVERY 연결
ALTER TABLE PRODUCT_ORDER
ADD FOREIGN KEY(DELIVERY_CD)
REFERENCES PRODUCT_DELIVERY(DELIVERY_CD);

-- PRODUCT_ORDER - CART 연결
ALTER TABLE PRODUCT_ORDER
ADD FOREIGN KEY(CART_NO)
REFERENCES CART(CART_NO);


-- 개별상품 결제 FK 추가

-- PRODUCT_PAY - MEMBER 연결
ALTER TABLE PRODUCT_PAY
ADD FOREIGN KEY(MEMBER_NO)
REFERENCES MEMBER(MEMBER_NO);

-- PRODUCT_PAY - PRODUCT_ORDER 연결
ALTER TABLE PRODUCT_PAY
ADD FOREIGN KEY(P_ORDER_CD)
REFERENCES PRODUCT_ORDER(P_ORDER_CD);


-- 개별상품 환불 FK 추가

-- PRODUCT_REFUND - PRODUCT_ORDER
ALTER TABLE PRODUCT_REFUND
ADD FOREIGN KEY(P_ORDER_CD)
REFERENCES PRODUCT_ORDER(P_ORDER_CD);

--------------------------------------------------------------------------------

-- 장바구니 FK 추가

-- CART - MEMBER 연결
ALTER TABLE CART
ADD FOREIGN KEY(MEMBER_NO)
REFERENCES MEMBER(MEMBER_NO);

-- CART - OPTION 연결
ALTER TABLE CART
ADD FOREIGN KEY(OPTION_NO)
REFERENCES OPTION_TB(OPTION_NO);

--------------------------------------------------------------------------------

-- 주문별 선택 옵션 FK 추가

-- OPTION_TB - OPTION_TYPE 연결
ALTER TABLE OPTION_TB
ADD FOREIGN KEY(OPTION_CD)
REFERENCES OPTION_TYPE(OPTION_CD);

-- OPTION_TB - PRODUCT_ORDER 연결
ALTER TABLE OPTION_TB
ADD FOREIGN KEY(P_ORDER_CD)
REFERENCES PRODUCT_ORDER(P_ORDER_CD);

-- 옵션 종류 FK 추가

-- OPTION_TYPE - PRODUCT 연결
ALTER TABLE OPTION_TYPE
ADD FOREIGN KEY(P_CD)
REFERENCES PRODUCT(P_CD);

--------------------------------------------------------------------------------

-- 구독 상품 주문 FK 추가

-- SUBS_ORDER - MEMBER 연결
ALTER TABLE SUBS_ORDER
ADD FOREIGN KEY(MEMBER_NO)
REFERENCES MEMBER(MEMBER_NO);

-- SUBS_ORDER - SUBS 연결
ALTER TABLE SUBS_ORDER
ADD FOREIGN KEY(S_CD)
REFERENCES SUBS(S_CD);

-- 구독 결제 FK 추가

-- SUBS_PAY - MEMBER 연결
ALTER TABLE SUBS_PAY
ADD FOREIGN KEY(MEMBER_NO)
REFERENCES MEMBER(MEMBER_NO);

-- SUBS_PAY - SUBS_ORDER 연결
ALTER TABLE SUBS_PAY
ADD FOREIGN KEY(S_ORDER_CD)
REFERENCES SUBS_ORDER(S_ORDER_CD);

-- 구독 배송 내역 FK 추가

-- SUBS_DELIVERY - PRODUCT_DELIVERY 연결
ALTER TABLE SUBS_DELIVERY
ADD FOREIGN KEY(DELIVERY_CD)
REFERENCES PRODUCT_DELIVERY(DELIVERY_CD);

-- SUBS_DELIVERY - SUBS_ORDER
ALTER TABLE SUBS_DELIVERY
ADD FOREIGN KEY(S_ORDER_CD)
REFERENCES SUBS_ORDER(S_ORDER_CD);

-- 제외 상품 FK 추가

-- SUBS_EXCEPTION - PRODUCT
ALTER TABLE SUBS_EXCEPTION
ADD FOREIGN KEY(P_CD)
REFERENCES PRODUCT(P_CD);

-- SUBS_EXCEPTION - SUBS_ORDER
ALTER TABLE SUBS_EXCEPTION
ADD FOREIGN KEY(S_ORDER_CD)
REFERENCES SUBS_ORDER(S_ORDER_CD);

--------------------------------------------------------------------------------

-- 상품 FK 추가

-- PRODUCT - P_CATEGORY 연결
ALTER TABLE PRODUCT
ADD FOREIGN KEY(P_CATEGORY_NO)
REFERENCES P_CATEGORY(P_CATEGORY_NO);

-- PRODUCT - FARM 연결
ALTER TABLE PRODUCT
ADD FOREIGN KEY(FARM_NO)
REFERENCES FARM(FARM_NO);

-- 상품 이미지 FK 추가

-- PRODUCT_IMG - PRODUCT 연결
ALTER TABLE PRODUCT_IMG
ADD FOREIGN KEY(P_CD)
REFERENCES PRODUCT(P_CD);

--------------------------------------------------------------------------------

-- 주별 상품 FK 추가

-- WEEKLY_P - PRODUCT
ALTER TABLE WEEKLY_P
ADD FOREIGN KEY(P_CD)
REFERENCES PRODUCT(P_CD);

-- WEEKLY_P - WEEKLY_LIST
ALTER TABLE WEEKLY_P
ADD FOREIGN KEY(P_LIST_NO)
REFERENCES WEEKLY_LIST(P_LIST_NO);

-- 상품 알림 FK 추가

-- P_MESSAGE - WEEKLY_LIST 연결
ALTER TABLE P_MESSAGE
ADD FOREIGN KEY(P_LIST_NO)
REFERENCES WEEKLY_LIST(P_LIST_NO);

-- P_MESSAGE - SUBS_ORDER 연결
ALTER TABLE P_MESSAGE
ADD FOREIGN KEY(S_ORDER_CD)
REFERENCES SUBS_ORDER(S_ORDER_CD);