SELECT * FROM FARM;

CREATE TABLE "FARM" (
   "FARM_NO"   NUMBER      NOT NULL,
   "FARM_NM"   VARCHAR2(100)      NOT NULL,
   "PRODUCER"   VARCHAR2(30)      NOT NULL,
   "ORIGIN"   VARCHAR2(100)      NOT NULL
);

INSERT INTO FARM VALUES(
    SEQ_FARM_NO.NEXTVAL, '옥수수농장', '옥수수쿵야', '초당마을' 
);

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_NAME"   VARCHAR2(20)      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(50)      NOT NULL,
   "MEMBER_ST"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "SECESSION_CNT"   VARCHAR2(100)      NULL
);

INSERT INTO MEMBER VALUES(
    SEQ_MEMBER_NO.NEXTVAL, '김민규', 'kmg@uglory.com', DEFAULT, NULL
);

SELECT * FROM MEMBER ORDER BY 1;
