


SELECT DISTINCT PRODUCT_NM, PRODUCT_PRICE, IMG_ROOT,
   P_CATEGORY_NM, PRODUCT_ST, P_CD, P_CATEGORY_NO,
   (SELECT COUNT(*) FROM REVIEW R2 WHERE R2.P_CD=P.P_CD) STAR_COUNT,
   
   CASE WHEN  (SELECT COUNT(*) FROM REVIEW R3 WHERE R3.P_CD=P.P_CD) = 0 THEN 0
        ELSE  ROUND((((SELECT SUM(STAR_RATING) FROM REVIEW R4 WHERE R4.P_CD=P.P_CD) / (SELECT COUNT(*) FROM REVIEW R5 WHERE R5.P_CD=P.P_CD))/2),1)
        END AS STAR_AVG
   
FROM PRODUCT P
LEFT JOIN REVIEW R ON(P.P_CD = R.P_CD)
LEFT JOIN PRODUCT_IMG I ON(P.P_CD = I.P_CD)
JOIN P_CATEGORY USING(P_CATEGORY_NO)
WHERE IMG_LEVEL='0';



WHERE P_CATEGORY_NO = #{selectCategoryNo}
AND IMG_LEVEL=0






SELECT P.P_CD,
ROUND((((SELECT SUM(STAR_RATING) FROM REVIEW R4 WHERE R4.P_CD=P.P_CD) / (SELECT COUNT(*) FROM REVIEW R5 WHERE R5.P_CD=P.P_CD))/2),1)
FROM PRODUCT P;

SELECT
ROUND(((A / B)/2),1)
FROM PRODUCT P;


SELECT * FROM REVIEW
WHERE P_CD=1;