CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_NO NOCACHE;
CREATE SEQUENCE SEQ_P_CD NOCACHE;
CREATE SEQUENCE SEQ_ADMIN_NO NOCACHE;
CREATE SEQUENCE SEQ_CART_NO NOCACHE;
CREATE SEQUENCE SEQ_P_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_P_ORDER_CD NOCACHE;
CREATE SEQUENCE SEQ_P_MESSAGE_NO NOCACHE;
CREATE SEQUENCE SEQ_P_LIST_NO NOCACHE;
CREATE SEQUENCE SEQ_FARM_NO NOCACHE;
CREATE SEQUENCE SEQ_OPTION_CD NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_NO NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_IMG NOCACHE;
CREATE SEQUENCE SEQ_DELIVERY_CD NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_IMG_NO NOCACHE;
CREATE SEQUENCE SEQ_P_PAY_NO NOCACHE;
CREATE SEQUENCE SEQ_S_PAY_NO NOCACHE;
CREATE SEQUENCE SEQ_S_ORDER_CD NOCACHE;
CREATE SEQUENCE SEQ_FAQ_CD NOCACHE;
CREATE SEQUENCE SEQ_FAQ_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_S_DELIVERY_CD NOCACHE;
CREATE SEQUENCE SEQ_OPTION_NO NOCACHE;
CREATE SEQUENCE SEQ_S_NO NOCACHE;
CREATE SEQUENCE SEQ_P_REFUND_CD NOCACHE;

INSERT INTO PRODUCT_DELIVERY
VALUES(SEQ_DELIVERY_CD.NEXTVAL, '배송완');

INSERT INTO PRODUCT
VALUES(SEQ_P_CD.NEXTVAL, 1, 1, '못난이바나나' , 15000, DEFAULT, '못난이 바나나 아주 맛나요~' , DEFAULT, SYSDATE);


INSERT INTO FARM
VALUES(SEQ_FARM_NO.NEXTVAL, '다영이네', '다영' , '제주도');

INSERT INTO P_CATEGORY
VALUES(SEQ_P_CATEGORY_NO.NEXTVAL, '과일류');

SELECT * FROM FARM;
SELECT * FROM P_CATEGORY;

SELECT PRODUCT_NM, ORIGIN

