CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

CREATE SEQUENCE SEQ_REVIEW_NO NOCACHE;
CREATE SEQUENCE SEQ_P_CD NOCACHE;
CREATE SEQUENCE SEQ_ADMIN_NO NOCACHE;
CREATE SEQUENCE SEQ_CART_NO NOCACHE;
CREATE SEQUENCE SEQ_P_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_P_ORDER_CD NOCACHE;
CREATE SEQUENCE SEQ_P_MESSAGE_NO NOCACHE;
CREATE SEQUENCE SEQ_P_LIST_NO NOCACHE;
CREATE SEQUENCE SEQ_FARM_NO NOCACHE;
CREATE SEQUENCE SEQ_OPTION_CD NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_NO NOCACHE;
CREATE SEQUENCE SEQ_PRODUCT_IMG NOCACHE;
CREATE SEQUENCE SEQ_DELIVERY_CD NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_IMG_NO NOCACHE;
CREATE SEQUENCE SEQ_P_PAY_NO NOCACHE;
CREATE SEQUENCE SEQ_S_PAY_NO NOCACHE;
CREATE SEQUENCE SEQ_S_ORDER_CD NOCACHE;
CREATE SEQUENCE SEQ_FAQ_CD NOCACHE;
CREATE SEQUENCE SEQ_FAQ_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_S_DELIVERY_CD NOCACHE;
CREATE SEQUENCE SEQ_OPTION_NO NOCACHE;
CREATE SEQUENCE SEQ_S_NO NOCACHE;
CREATE SEQUENCE SEQ_P_REFUND_CD NOCACHE;

INSERT INTO PRODUCT_DELIVERY
VALUES(SEQ_DELIVERY_CD.NEXTVAL, '배송완');

INSERT INTO PRODUCT
VALUES(SEQ_P_CD.NEXTVAL, 1, 1, '못난이바나나' , 15000, DEFAULT, '못난이 바나나 아주 맛나요~' , DEFAULT, SYSDATE);


INSERT INTO FARM
VALUES(SEQ_FARM_NO.NEXTVAL, '다영이네', '다영' , '제주도');

INSERT INTO P_CATEGORY
VALUES(SEQ_P_CATEGORY_NO.NEXTVAL, '과일류');

SELECT * FROM FARM;
SELECT * FROM P_CATEGORY;

SELECT PRODUCT_NM, ORIGIN

ALTER TABLE MEMBER
DROP COLUMN SECESSION_CNT;

DROP TABLE SECESSION_CNT;

CREATE TABLE "SECESSION_CNT" (
	"SECESSION_CD"	NUMBER	NOT NULL,
	"SECESSION_CNT"	VARCHAR2(200)	NOT NULL
   
);
ALTER TABLE MEMBER add (SECESSION_CD NUMBER); 
SELECT * FROM MEMBER;

ALTER TABLE "SECESSION_CNT" ADD CONSTRAINT "PK_SECESSION_CNT" PRIMARY KEY (
	"SECESSION_CD"
);

COMMENT ON COLUMN "SECESSION_CNT"."SECESSION_CD" IS '회원 탈퇴 코드';
COMMENT ON COLUMN "SECESSION_CNT"."SECESSION_CNT" IS '회원 탈퇴 사유 내용';


INSERT INTO SECESSION_CNT VALUES(1, '더 이상 서비스가 필요하지 않아요.');
INSERT INTO SECESSION_CNT VALUES(2, '서비스가 마음에 들지 않아요.');
INSERT INTO SECESSION_CNT VALUES(3, '구독료가 부담스러워요.');
INSERT INTO SECESSION_CNT VALUES(4, '비밀!!');


SELECT * FROM SECESSION_CNT;

