SELECT * FROM FARM;

CREATE TABLE "FARM" (
   "FARM_NO"   NUMBER      NOT NULL,
   "FARM_NM"   VARCHAR2(100)      NOT NULL,
   "PRODUCER"   VARCHAR2(30)      NOT NULL,
   "ORIGIN"   VARCHAR2(100)      NOT NULL
);

INSERT INTO FARM VALUES(
    SEQ_FARM_NO.NEXTVAL, '옥수수농장', '옥수수쿵야', '초당마을' 
);

CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER      NOT NULL,
   "MEMBER_NAME"   VARCHAR2(20)      NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(50)      NOT NULL,
   "MEMBER_ST"   CHAR(1)   DEFAULT 'N'   NOT NULL,
   "SECESSION_CNT"   VARCHAR2(100)      NULL
);

INSERT INTO MEMBER VALUES(
    SEQ_MEMBER_NO.NEXTVAL, '김민규', 'kmg@uglory.com', DEFAULT, NULL
);

SELECT * FROM MEMBER ORDER BY 1;


-- 1,2 밖에 없음!! 
INSERT INTO SUBS VALUES(
   '2', '점보', '24000'
); 


INSERT INTO SUBS_ORDER VALUES(
   SEQ_S_ORDER_CD.NEXTVAL, DEFAULT, DEFAULT, '김민규', 
   '01017171717', '우리집', '빨리조심',
   SYSDATE, DEFAULT, '2', 1, '1'
);

SELECT * FROM SUBS_ORDER;

SELECT M.MEMBER_NO, M.MEMBER_EMAIL, M.MEMBER_NAME, S.S_CANCEL, M.MEMBER_ST
FROM MEMBER M
LEFT JOIN SUBS_ORDER S
ON M.MEMBER_NO = S.MEMBER_NO
WHERE MEMBER_ST = 'N'
ORDER BY 1;

SELECT * FROM MEMBER;

ALTER TABLE ADMIN
MODIFY ADMIN_PW VARCHAR(100);




SELECT M.MEMBER_NO, M.MEMBER_EMAIL, M.MEMBER_NAME, S.S_CANCEL, M.MEMBER_ST
FROM MEMBER M
LEFT JOIN SUBS_ORDER S
ON M.MEMBER_NO = S.MEMBER_NO
WHERE MEMBER_ST = 'N'
AND MEMBER_NAME LIKE '%이%'
ORDER BY MEMBER_NO;

